version: "3.7"

services:
  elsa-demo:
    build:
      context: .
      args:
        - api_queue=infl-expectations
        - rmq_connect=amqp://:@localhost:5672
      network: host
    command: "python /root/server/server.py -c /root/server/config.json && python /root/run.py -c /root/config.json"
    container_name: infl-api
    network_mode: host
    restart: always
